name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "danijeljw" --password-stdin
        docker build . --file Dockerfile --tag repasscloud/optechx-webui:latest
        docker push repasscloud/optechx-webui:latest
